[network_zenoh]
ca_cert = """
-----BEGIN CERTIFICATE-----
MIIBdTCCARqgAwIBAgIUApODf1cbs6bQHLIv+eU9jRSFNUswCgYIKoZIzj0EAwIw
HzEQMA4GA1UECgwHQ0lUQUh1YjELMAkGA1UEAxMCQ0EwIBcNNzUwMTAxMDAwMDAw
WhgPNDA5NjAxMDEwMDAwMDBaMB8xEDAOBgNVBAoMB0NJVEFIdWIxCzAJBgNVBAMT
AkNBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEakXuejIqzqNCbrBoxy2xlQiX
eEgi6MkHBmQ/ELgJmPQ/o2/omilNvxN3IfXdz6pGUa5gE4ofDTXKPjakmf93pKMy
MDAwHQYDVR0OBBYEFAKTg39XG7Om0ByyL/nlPY0UhTVLMA8GA1UdEwEB/wQFMAMB
Af8wCgYIKoZIzj0EAwIDSQAwRgIhALtwNKc4DcTujVUSRklLgey1IuI6Prx+wmwL
HUabai74AiEAiAwifkHU6beOEu715FFUF8eVJnIodw6qjVro0yCXOrw=
-----END CERTIFICATE-----
"""
cert = """
-----BEGIN CERTIFICATE-----
MIIBaTCCAQ6gAwIBAgIVAJTxZ5fQIiMGyJNwA7WGZ3+JIYbmMAoGCCqGSM49BAMC
MB8xEDAOBgNVBAoMB0NJVEFIdWIxCzAJBgNVBAMTAkNBMCAXDTc1MDEwMTAwMDAw
MFoYDzQwOTYwMTAxMDAwMDAwWjApMRAwDgYDVQQKDAdDSVRBSHViMRUwEwYDVQQD
Ewx0ZXN0LWNoYWluLTAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARxf/u8sDkw
qV/dOJtQpJJB+0iHMONQUutUFl4EextmxP+VpfREXUwE3D6TWNww4X8BtWDZTE8w
fzcQlQ4IrAPDoxswGTAXBgNVHREEEDAOggx0ZXN0LWNoYWluLTAwCgYIKoZIzj0E
AwIDSQAwRgIhANccWlRRrHNvvhn6G84cVHKSWsAr5/7vPJJS3q+6DufNAiEAmwAA
wGl9Epdi8aHVkANIjlVSxCqaels16p7B7v4vXFU=
-----END CERTIFICATE-----
"""
chain_id = "63586a3c0255f337c77a777ff54f0040b8c388da04f23ecee6bfd4953a6512b4"
domain = "test-chain-0"
enable_metrics = true
grpc_port = 50000
metrics_port = 60000
node_address = "node_address"
port = 40000
priv_key = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgtH6N4MrNHQ/uaCuN
wjOo1O/ZlXNMJkZiimQ8Ek7JqRKhRANCAARxf/u8sDkwqV/dOJtQpJJB+0iHMONQ
UutUFl4EextmxP+VpfREXUwE3D6TWNww4X8BtWDZTE8wfzcQlQ4IrAPD
-----END PRIVATE KEY-----
"""
protocol = "quic"
validator_address = "validator_address"

[[network_zenoh.modules]]
hostname = "127.0.0.1"
module_name = "consensus"
port = 50001

[[network_zenoh.modules]]
hostname = "127.0.0.1"
module_name = "controller"
port = 50004

[[network_zenoh.peers]]
domain = "test-chain-1"
port = 40001
protocol = "quic"

[[network_zenoh.peers]]
domain = "test-chain-2"
port = 40002
protocol = "quic"

[[network_zenoh.peers]]
domain = "test-chain-3"
port = 40003
protocol = "quic"

[network_zenoh.log_config]
filter = "info"
max_level = "info"
rolling_file_path = "./logs"
service_name = "network"

[consensus_overlord]
consensus_port = 50001
controller_port = 50004
domain = "test-chain-0"
enable_metrics = true
metrics_port = 60001
network_port = 50000

[consensus_overlord.log_config]
filter = "info"
max_level = "info"
rolling_file_path = "./logs"
service_name = "consensus"

[executor_evm]
domain = "test-chain-0"
enable_metrics = true
executor_port = 50002
metrics_port = 60002

[executor_evm.log_config]
filter = "info"
max_level = "info"
rolling_file_path = "./logs"
service_name = "executor"

[storage_opendal]
domain = "test-chain-0"
enable_metrics = true
metrics_port = 60003
storage_port = 50003

[storage_opendal.cloud_storage]
access_key_id = ""
bucket = ""
endpoint = ""
root = ""
secret_access_key = ""
service_type = ""

[storage_opendal.log_config]
filter = "info"
max_level = "info"
rolling_file_path = "./logs"
service_name = "storage"

[genesis_block]
prevhash = "0x0000000000000000000000000000000000000000000000000000000000000000"
timestamp = 1731491738494

[system_config]
admin = "a2ec545396052868038a2d9e45f1e36862d3a96f"
block_interval = 3
block_limit = 100
chain_id = "63586a3c0255f337c77a777ff54f0040b8c388da04f23ecee6bfd4953a6512b4"
quota_limit = 1073741824
validators = [
    "b7d2b81cfcca311afbc1b9c7828f2470ae93bf7cce37f82d15ab5281832b4b41903eed95673a5671944d3a4a3546fd58",
    "88d54074bb66ff5b2d493accd3345f37f938abb50086663da5538e20ed9f05f6075a5e16f4ea8eb830cdc12e5a6ed506",
    "b0bee217188e7fd46c8d31ed2d11eddc64066592fa08f8c58d468f0c0b71fdbf528ba06c76746997298880642330246f",
    "9919d826eacb603d2422ef93a01c8c9813fd911895d6f3a6e50238e35df8f98a24b8e1ac1ea02f98f876c19a8e4dbd2b",
]
version = 0

[controller]
consensus_port = 50001
controller_port = 50004
domain = "test-chain-0"
enable_metrics = true
executor_port = 50002
is_danger = false
metrics_port = 60004
network_port = 50000
node_address = "node_address"
storage_port = 50003
validator_address = "validator_address"

[controller.log_config]
filter = "info"
max_level = "info"
rolling_file_path = "./logs"
service_name = "controller"

